// grammar/test.lark
?start: abbreviated_syntax
      | xpath_syntax

?abbreviated_syntax: p
                   | n

?p: s
  | p "/" p -> axis_child
  | p "//" p -> axis_descendant
  | p "U" p

?s: step_abbreviated
  | s "[" n "]"

?step_abbreviated: "." -> axis_self
                 | ".." -> axis_parent
                 | "@" LAB -> axis_attribute
                 | "@ *" -> axis_attribute
                 | "text()" -> axis_child_text
                 | "node()" -> axis_child_node
                 | LAB
                 | "*"

?n: "?" p
  | "(" "lab" "=" LAB ")" -> lab
  | "(" "lab" "=" "*" ")" -> lab
  | "(" n "&" n ")" -> and
  | "(" n "|" n ")" -> or
  | "!" n -> not

?xpath_syntax: pe -> pe
             | ne -> ne

?pe: step
   | "(" pe "/" pe ")"
   | "(" pe "U" pe ")"

?step: axis
     | step "[" ne "]"

?ne: "?" pe
   | "(" "lab" "=" LAB ")" -> lab
   | "(" "lab" "=" "*" ")" -> lab
   | "(" ne "&" ne ")" -> and
   | "(" ne "|" ne ")" -> or
   | "!" ne -> not

axis: "self" -> axis_self
    | "descendant" -> axis_descendant
    | "next-sibling" -> axis_next_sibling
    | "following" -> axis_following
    | "child" -> axis_child
    | "descendant-or-self" -> axis_descendant_or_self
    | "following-sibling" -> axis_following_sibling
    | "preceding" -> axis_preceding
    | "parent" -> axis_parent
    | "ancestor" -> axis_ancestor
    | "previous-sibling" -> axis_previous_sibling
    | "ancestor-or-self" -> axis_ancestor_or_self
    | "preceding-sibling" -> axis_preceding_sibling

// We can expand this later to support wildcards or namespaces.
LAB: CNAME

%import common.CNAME
%import common.WS
%ignore WS